// =============================================================================
// dadosPosGraduacao.ts
// Fonte de dados dos cursos de pós-graduação da CQP.
// Separe os dados do componente para manter o .tsx limpo e focado em UI.
// =============================================================================

import { type Curso } from '../../data/cursos';

function p(id: string, nome: string, extra?: string): Curso {
  return {
    id,
    nome,
    categoria: 'pos-graduacoes',
    imagem: '/images/cursos-pos/capa-padrao-pos.png',
    modalidades: ['online'],
    extra,
  };
}

export const CURSOS_POS_GRADUACAO: Curso[] = [
  p('pos-cultura-lazer', 'A Cultura e Lazer Cultura'),
  p('pos-psicologia-contos-fada', 'A Psicologia dos Contos de Fada'),
  p('pos-adm-supervisao-escolar', 'Administração e Supervisão Escolar'),
  p('pos-adm-publica', 'Administração Pública'),
  p('pos-agronegocios', 'Agronegócios'),
  p('pos-alfabetizacao-letramento', 'Alfabetização e Letramento'),
  p('pos-alfabetizacao-letramento-ii', 'Alfabetização e Letramento II'),
  p('pos-andragogia', 'Andragogia: Formação de Jovens e Adultos'),
  p('pos-arbitragem-mediacao', 'Arbitragem e Mediação de Conflitos'),
  p('pos-arte-contar-historia', 'Arte de Contar História'),
  p('pos-arte-cultura', 'Arte e Cultura'),
  p('pos-arte-educacao', 'Arte-Educação'),
  p('pos-arteterapia', 'Arteterapia'),
  p('pos-aee', 'Atendimento Educacional Especializado - AEE'),
  p('pos-aee-autismo', 'Atendimento Educacional Especializado com Ênfase em Autismo'),
  p('pos-ubs-enfermagem', 'Atendimento na Unidade Básica de Saúde - Enfermagem'),
  p('pos-ubs-nutricao', 'Atendimento na Unidade Básica de Saúde - Nutrição'),
  p('pos-avaliacao-psicologica', 'Avaliação Psicológica e Psicodiagnóstico'),
  p('pos-biomedicina-estetica', 'Biomedicina Estética'),
  p('pos-braille', 'Braille'),
  p('pos-ciencias-meio-ambiente', 'Ciências e Meio Ambiente Aplicado à Educação'),
  p('pos-ciencias-naturais', 'Ciências Naturais e Sustentabilidade na Educação'),
  p('pos-ciencias-sociais-geografia', 'Ciências Sociais e Ensino de Geografia'),
  p('pos-compliance', 'Compliance'),
  p('pos-comportamento-neurociencia', 'Comportamento Humano e Neurociência'),
  p('pos-coordenacao-orientacao-escolar', 'Coordenação e Orientação Escolar'),
  p('pos-coordenacao-educacional', 'Coordenação Educacional'),
  p('pos-criminologia', 'Criminologia'),
  p('pos-cuidados-paliativos', 'Cuidados Paliativos'),
  p('pos-diagnostico-avaliacao-psicologica', 'Diagnóstico e Avaliação Psicológica'),
  p('pos-direito-administrativo', 'Direito Administrativo'),
  p('pos-direito-ambiental', 'Direito Ambiental'),
  p('pos-direito-civil-processual', 'Direito Civil e Processual Civil'),
  p('pos-direito-familia', 'Direito da Família'),
  p('pos-direito-trabalho', 'Direito do Trabalho'),
  p('pos-direito-transito', 'Direito do Trânsito'),
  p('pos-direito-educacional', 'Direito Educacional'),
  p('pos-direito-eleitoral', 'Direito Eleitoral'),
  p('pos-direito-empresarial', 'Direito Empresarial'),
  p('pos-direitos-humanos-pericia', 'Direito Humanos e Perícia Criminal'),
  p('pos-direito-imobiliario', 'Direito Imobiliário'),
  p('pos-direito-penal-processual', 'Direito Penal e Processo Penal'),
  p('pos-direito-penal-militar', 'Direito Penal Militar'),
  p('pos-direito-previdenciario', 'Direito Previdenciário'),
  p('pos-direito-processual-civil', 'Direito Processual Civil'),
  p('pos-direito-publico', 'Direito Público: Constitucional, Administrativo e Tributário'),
  p('pos-direito-tributario-processual', 'Direito Tributário e Processual Tributário'),
  p('pos-docencia-superior-gestao-tutoria', 'Docência do Ensino Superior, Gestão e Tutoria EAD'),
  p('pos-docencia-enfermagem', 'Docência em Enfermagem'),
  p('pos-docencia-basica-infantil', 'Docência na Educação Básica e Infantil'),
  p('pos-docencia-ensino-superior', 'Docência no Ensino Superior'),
  p('pos-docencia-superior-medio-tecnico', 'Docência no Ensino Superior, Médio e Técnico'),
  p('pos-educacao-5', 'Educação 5.0'),
  p('pos-educacao-distancia', 'Educação a Distância'),
  p('pos-educacao-distancia-pos', 'Educação a Distância - Pós'),
  p('pos-educacao-distancia-ii', 'Educação à Distância II'),
  p('pos-educacao-ambiental-pos', 'Educação Ambiental - Pós'),
  p('pos-educacao-ambiental-sustentabilidade', 'Educação Ambiental e Sustentabilidade'),
  p('pos-educacao-jovens-adultos', 'Educação de Jovens e Adultos'),
  p('pos-educacao-movimentos-sociais', 'Educação e Movimentos Sociais'),
  p('pos-educacao-foco', 'Educação em Foco'),
  p('pos-educacao-tempo-integral', 'Educação em Tempo Integral'),
  p('pos-educacao-unidades-saude', 'Educação em Unidades de Saúde'),
  p('pos-educacao-especial-pos', 'Educação Especial - Pós'),
  p('pos-educacao-especial-avancado', 'Educação Especial Avançado'),
  p('pos-educacao-especial-inclusiva', 'Educação Especial e Inclusiva'),
  p('pos-educacao-financeira-matematica', 'Educação Financeira e Matemática Aplicada'),
  p('pos-educacao-fisica-adaptada', 'Educação Física Adaptada e Inclusiva'),
  p('pos-educacao-fisica-escolar', 'Educação Física Escolar'),
  p('pos-educacao-fisica-especial', 'Educação Física Escolar com Ênfase em Educação Especial'),
  p('pos-educacao-fisica-treinamento', 'Educação Física Escolar e Treinamento Desportivo'),
  p('pos-educacao-fisica-recreacao', 'Educação Física, Escolar e Recreação'),
  p('pos-educacao-inclusiva-pos', 'Educação Inclusiva - Pós'),
  p('pos-educacao-inclusiva-acessibilidade', 'Educação Inclusiva e Acessibilidade'),
  p('pos-educacao-inclusiva-diversidade', 'Educação Inclusiva e Diversidade Cultural'),
  p('pos-educacao-infantil', 'Educação Infantil'),
  p('pos-educacao-infantil-pos', 'Educação Infantil - Pós Graduação'),
  p('pos-educacao-infantil-0-5', 'Educação Infantil de 0 a 5 Anos'),
  p('pos-educacao-infantil-alfabetizacao', 'Educação Infantil, Alfabetização e Letramento'),
  p('pos-educacao-infantil-especial-tgd', 'Educação Infantil, Especial e TGD'),
  p('pos-educacao-matematica', 'Educação Matemática'),
  p('pos-educacao-musical-arte', 'Educação Musical e o Ensino de Arte'),
  p('pos-educacao-diversidade-cidadania', 'Educação para a Diversidade e Cidadania'),
  p('pos-educacao-psicomotora', 'Educação Psicomotora'),
  p('pos-educacao-socioemocional', 'Educação Socioemocional nas Escolas'),
  p('pos-geografia-humana', 'Educação: Geografia Humana'),
  p('pos-emergencias-pediatricas', 'Emergências Pediátricas'),
  p('pos-enfermagem-trabalho', 'Enfermagem do Trabalho'),
  p('pos-enfermagem-trabalho-saude', 'Enfermagem do Trabalho e Saúde Ocupacional'),
  p('pos-enfermagem-oncologia', 'Enfermagem em Oncologia'),
  p('pos-enfermagem-urgencia', 'Enfermagem em Urgência e Emergência'),
  p('pos-engenharia-ambiental', 'Engenharia Ambiental'),
  p('pos-engenharia-ambiental-energias', 'Engenharia Ambiental e Energias Renováveis'),
  p('pos-engenharia-ambiental-saneamento', 'Engenharia Ambiental e Saneamento Básico'),
  p('pos-engenharia-manutencao', 'Engenharia de Manutenção'),
  p('pos-engenharia-seguranca-trabalho', 'Engenharia de Segurança do Trabalho'),
  p('pos-engenharia-suprimentos', 'Engenharia de Suprimentos'),
  p('pos-ensino-artes', 'Ensino de Artes'),
  p('pos-ensino-ciencias-matematica', 'Ensino de Ciências e Matemática nas Séries Iniciais do Ensino Fundamental'),
  p('pos-ensino-linguas', 'Ensino de Línguas na Educação'),
  p('pos-ensino-religioso', 'Ensino Religioso'),
  p('pos-aba-autismo', 'Especialização em Análise do Comportamento Aplicada ao Autismo (ABA)'),
  p('pos-comunicacao-oratoria', 'Especialização em Comunicação e Oratória'),
  p('pos-educ-especial-tea', 'Especialização em Educ. Especial Inclusiva e Transtorno do Espectro Autista (TEA)'),
  p('pos-engenharia-qualidade', 'Especialização em Engenharia da Qualidade'),
  p('pos-engenharia-sanitaria', 'Especialização em Engenharia Sanitária e Ambiental'),
  p('pos-instrumentacao-cirurgica', 'Especialização em Instrumentação Cirúrgica'),
  p('pos-metodologia-historia', 'Especialização em Metodologia do Ensino de História'),
  p('pos-metodologia-lingua-portuguesa', 'Especialização em Metodologia do Ensino de Língua Portuguesa'),
  p('pos-estatistica-aplicada', 'Estatística Aplicada'),
  p('pos-estetica-cosmetologia', 'Estética e Cosmetologia'),
  p('pos-estetica-historia-arte', 'Estética e História da Arte'),
  p('pos-farmacia-clinica-hospitalar', 'Farmácia Clínica e Hospitalar'),
  p('pos-farmacia-estetica', 'Farmácia Estética'),
  p('pos-formacao-profissao-docente', 'Formação e Profissão Docente'),
  p('pos-gamificacao-aprendizagem', 'Gamificação e Aprendizagem Ativa'),
  p('pos-gestao-escolar-integrada', 'Gestão Escolar Integrada com Ênfase em Supervisão, Orientação, Administração e Inspeção'),
  p('pos-gestao-ambiental-sustentavel', 'Gestão Ambiental Sustentável'),
  p('pos-gestao-bancaria-negocios', 'Gestão Bancária e Negócios'),
  p('pos-gestao-clinicas-consultorias', 'Gestão de Clínicas e Consultórias'),
  p('pos-gestao-clinicas-consultorios', 'Gestão de Clínicas e Consultórios'),
  p('pos-gestao-clinicas-odontologicas', 'Gestão de Clínicas Odontológicas'),
  p('pos-gestao-investimento', 'Gestão de Investimento'),
  p('pos-gestao-marketing-digital', 'Gestão de Marketing Digital'),
  p('pos-gestao-processos-producao', 'Gestão de Processos de Produção'),
  p('pos-gestao-planejamento-projetos-sociais', 'Gestão e Planejamento de Projetos Sociais'),
  p('pos-gestao-educacional', 'Gestão Educacional'),
  p('pos-gestao-educacional-pos', 'Gestão Educacional - Pós'),
  p('pos-gestao-educacional-inclusao', 'Gestão Educacional com Foco na Inclusão'),
  p('pos-gestao-educacional-inspecao', 'Gestão Educacional e Inspeção Escolar'),
  p('pos-gestao-logistica', 'Gestão em Logística'),
  p('pos-gestao-qualidade-saude', 'Gestão em Qualidade em Serviço de Saúde e Hospitalar'),
  p('pos-gestao-recursos-humanos', 'Gestão em Recursos Humanos'),
  p('pos-gestao-saude-publica', 'Gestão em Saúde Pública'),
  p('pos-gestao-escolar', 'Gestão Escolar'),
  p('pos-gestao-escolar-adm-educacional', 'Gestão Escolar e Administração Educacional'),
  p('pos-gestao-escolar-coordenacao', 'Gestão Escolar e Coordenação Pedagógica'),
  p('pos-gestao-licenciamento-auditoria', 'Gestão, Licenciamento e Auditoria Ambiental'),
  p('pos-gestao-supervisao-inspecao', 'Gestão, Supervisão, Inspeção e Orientação Escolar'),
  p('pos-historia-educacao', 'História da Educação'),
  p('pos-historia-cultura-brasil', 'História e Cultura no Brasil'),
  p('pos-historia-sociedade-educacao', 'História e Sociedade na Educação'),
  p('pos-humanidades-sociedade-etica', 'Humanidades, Sociedade e Ética'),
  p('pos-informatica-educacao', 'Informática na Educação'),
  p('pos-inovacao-pedagogica', 'Inovação Pedagógica com Tecnologias Emergentes'),
  p('pos-instalacao-energia-solar', 'Instalação de Sistemas de Energia Solar'),
  p('pos-inteligencia-artificial', 'Inteligência Artificial'),
  p('pos-leitura-producao-textual', 'Leitura e Produção Textual no Ensino Fundamental'),
  p('pos-letras-portugues-literatura', 'Letras - Português e Literatura'),
  p('pos-libras', 'Libras - Língua Brasileira de Sinais'),
  p('pos-lingua-literatura-brasileira', 'Língua e Literatura Brasileira'),
  p('pos-linguistica-ensino-linguas', 'Linguística e Ensino de Línguas na Educação Básica'),
  p('pos-linguistica-estudo-linguagens', 'Linguística e o Estudo das Linguagens'),
  p('pos-literacia-comunicacao', 'Literacia e Comunicação'),
  p('pos-literatura-infantojuvenil', 'Literatura Infantojuvenil e Práticas Pedagógicas'),
  p('pos-ludopedagogia', 'Ludopedagogia'),
  p('pos-matematica-cultura-africana', 'Matemática e Cultura Africana na Educação Básica'),
  p('pos-matematica-financeira-estatistica', 'Matemática Financeira e Estatística'),
  p('pos-mba-adm-financeira', 'MBA - Administração Financeira e Orçamentária'),
  p('pos-mba-compliance-riscos', 'MBA - Compliance e Gestão de Riscos'),
  p('pos-mba-engenharia-producao', 'MBA - Engenharia de Produção'),
  p('pos-mba-gestao-pessoal', 'MBA - Gestão de Departamento Pessoal e Relações Trabalhistas'),
  p('pos-mba-gestao-pessoas-lideranca', 'MBA - Gestão de Pessoas e Liderança'),
  p('pos-mba-gestao-empresarial', 'MBA - Gestão Empresarial'),
  p('pos-mba-adm-hospitalar', 'MBA em Administração Hospitalar'),
  p('pos-mba-arbitragem-conciliacao', 'MBA em Arbitragem, Conciliação e Mediação'),
  p('pos-mba-assessoria-comunicacao', 'MBA em Assessoria de Comunicação'),
  p('pos-mba-auditoria', 'MBA em Auditoria'),
  p('pos-mba-auditoria-contabil', 'MBA em Auditoria Contábil'),
  p('pos-mba-auditoria-pericia', 'MBA em Auditoria e Perícia Contábil'),
  p('pos-mba-auditoria-saude', 'MBA em Auditoria em Saúde'),
  p('pos-mba-coaching', 'MBA em Coaching'),
  p('pos-mba-comunicacao-eleitoral', 'MBA em Comunicação Eleitoral e Marketing Político'),
  p('pos-mba-contabilidade-gerencial', 'MBA em Contabilidade Gerencial'),
  p('pos-mba-controladoria-financas', 'MBA em Controladoria e Finanças'),
  p('pos-mba-controladoria-financeira', 'MBA em Controladoria Financeira'),
  p('pos-mba-ecommerce', 'MBA em E-Commerce'),
  p('pos-mba-educacao-financeira', 'MBA em Educação Financeira'),
  p('pos-mba-esg', 'MBA em ESG – Environmental, Social & Governance'),
  p('pos-mba-gestao-ambiental', 'MBA em Gestão Ambiental'),
  p('pos-mba-gestao-aplicada-engenharia', 'MBA em Gestão Aplicada à Engenharia'),
  p('pos-mba-gestao-comercial', 'MBA em Gestão Comercial'),
  p('pos-mba-gestao-producao', 'MBA em Gestão da Produção'),
  p('pos-mba-gestao-saude-colaborador', 'MBA em Gestão da Saúde Física e Mental do Colaborador'),
  p('pos-mba-gestao-clinicas-psicologia', 'MBA em Gestão de Clínicas de Psicologia'),
  p('pos-mba-gestao-clinicas-veterinarios', 'MBA em Gestão de Clínicas e Consultórios Veterinários'),
  p('pos-mba-gestao-custos-financas', 'MBA em Gestão de Custos e Finanças'),
  p('pos-mba-gestao-drogaria-farmacia', 'MBA em Gestão de Drogaria e Farmácia'),
  p('pos-mba-gestao-eventos', 'MBA em Gestão de Eventos'),
  p('pos-mba-gestao-negocios-imobiliarios', 'MBA em Gestão de Negócios Imobiliários'),
  p('pos-mba-gestao-negocios-inovadores', 'MBA em Gestão de Negócios Inovadores'),
  p('pos-mba-gestao-negocios-internacionais', 'MBA em Gestão de Negócios Internacionais e Comércio Exterior'),
  p('pos-mba-gestao-obras-qualidade', 'MBA em Gestão de Obras, Qualidade e Desempenho das Construções'),
  p('pos-mba-gestao-processos', 'MBA em Gestão de Processos'),
  p('pos-mba-gestao-projetos', 'MBA em Gestão de Projetos'),
  p('pos-mba-gestao-projetos-aprendizagem', 'MBA em Gestão de Projetos de Aprendizagem'),
  p('pos-mba-gestao-seguros-previdencia', 'MBA em Gestão de Seguros e Previdência Privada'),
  p('pos-mba-gestao-servicos', 'MBA em Gestão de Serviços'),
  p('pos-mba-gestao-turismo', 'MBA em Gestão de Turismo e Hospitalidade'),
  p('pos-mba-gestao-vendas', 'MBA em Gestão de Vendas'),
  p('pos-mba-gestao-agronegocio', 'MBA em Gestão do Agronegócio'),
  p('pos-mba-gestao-desenvolvimento-colaborador', 'MBA em Gestão do Desenvolvimento do Colaborador'),
  p('pos-mba-gestao-retorno-financeiro', 'MBA em Gestão do Retorno Financeiro de Talentos nos Negócios'),
  p('pos-mba-gestao-estrategica-cooperativas', 'MBA em Gestão Estratégica de Cooperativas'),
  p('pos-mba-gestao-estrategica-compras', 'MBA em Gestão Estratégica em Compras'),
  p('pos-mba-gestao-estrategica-esg', 'MBA em Gestão Estratégica em ESG'),
  p('pos-mba-gestao-fiscal-tributaria', 'MBA em Gestão Fiscal e Tributária'),
  p('pos-mba-gestao-hospitalar', 'MBA em Gestão Hospitalar'),
  p('pos-mba-gestao-publica', 'MBA em Gestão Pública'),
  p('pos-mba-inteligencia-comercial', 'MBA em Inteligência Comercial e de Mercado'),
  p('pos-mba-jornalismo-digital', 'MBA em Jornalismo Digital'),
  p('pos-mba-logistica-supply-chain', 'MBA em Logística e Supply Chain Management'),
  p('pos-mba-marketing-varejo', 'MBA em Marketing de Varejo, Gestão, Estratégias e Negócios'),
  p('pos-mba-marketing-estrategico-digital', 'MBA em Marketing Estratégico Digital'),
  p('pos-mba-mediacao-gestao-conflitos', 'MBA em Mediação e Gestão de Conflitos'),
  p('pos-mba-planejamento-abertura-negocio', 'MBA em Planejamento para Abertura de Negócio'),
  p('pos-mba-prescricao-estetica', 'MBA em Prescrição Estética'),
  p('pos-mba-relacoes-internacionais', 'MBA em Relações Internacionais'),
  p('pos-mba-seguranca-publica', 'MBA em Segurança Pública'),
  p('pos-mba-startups-inovacao', 'MBA em Startups e Inovação'),
  p('pos-mediacao-cultural-educacao', 'Mediação Cultural e Educação'),
  p('pos-mediacao-tutoria-ead', 'Mediação e Tutoria na Educação a Distância'),
  p('pos-metodologia-matematica-fisica', 'Metodologia do Ensino da Matemática e Física'),
  p('pos-metodologia-educacao-fisica', 'Metodologia do Ensino de Educação Física'),
  p('pos-metodologia-ensino-ingles', 'Metodologia do Ensino de Inglês'),
  p('pos-metodologia-superior-modalidades', 'Metodologia do Ensino Superior nas Várias Modalidades'),
  p('pos-metodologias-ativas-docente', 'Metodologias Ativas e Prática Docente'),
  p('pos-metodologias-ativas-tecnologias', 'Metodologias Ativas e Tecnologias Educacionais'),
  p('pos-metodologias-ensino-matematica', 'Metodologias do Ensino de Matemática'),
  p('pos-microbiologia', 'Microbiologia'),
  p('pos-mundo-digital-tecnologias', 'Mundo Digital e Tecnologias para Educação'),
  p('pos-neurociencia-aprendizagem-infantil', 'Neurociência e Aprendizagem na Educação Infantil'),
  p('pos-neuropsicologia', 'Neuropsicologia'),
  p('pos-neuropsicologia-clinica', 'Neuropsicologia Clínica'),
  p('pos-neuropsicopedagogia', 'Neuropsicopedagogia'),
  p('pos-neuropsicopedagogia-clinica', 'Neuropsicopedagogia Clínica'),
  p('pos-nutricao-esportiva', 'Nutrição Esportiva'),
  p('pos-orientacao-educacional', 'Orientação Educacional'),
  p('pos-pedagogia-empresarial', 'Pedagogia Empresarial e Educação Corporativa'),
  p('pos-pericia-auditoria-contabil', 'Perícia e Auditoria Contábil'),
  p('pos-pericia-economica-financeira', 'Perícia Econômica Financeira'),
  p('pos-planejamento-gestao-transito', 'Planejamento e Gestão de Trânsito'),
  p('pos-direitos-humanos-pos', 'Pós-Graduação em Direitos Humanos'),
  p('pos-direito-administrativo-pos', 'Pós-Graduação em Direito Administrativo'),
  p('pos-direito-constitucional-pos', 'Pós-Graduação em Direito Constitucional'),
  p('pos-direito-tributario-pos', 'Pós-Graduação em Direito Tributário'),
  p('pos-gerontologia-idoso', 'Pós-Graduação em Gerontologia e Gestão da Assistência ao Idoso'),
  p('pos-gestao-qualidade-pos', 'Pós-Graduação em Gestão da Qualidade'),
  p('pos-gestao-ti-pos', 'Pós-Graduação em Gestão da Tecnologia de Informação'),
  p('pos-gestao-rh-pos', 'Pós-Graduação em Gestão de Recursos Humanos'),
  p('pos-gestao-riscos-ciberseguranca', 'Pós-Graduação em Gestão de Riscos e Cibersegurança'),
  p('pos-gestao-estrategica-pessoas', 'Pós-Graduação em Gestão Estratégica de Pessoas'),
  p('pos-lideranca-desenvolvimento-equipes', 'Pós-Graduação em Liderança e Desenvolvimento de Equipes'),
  p('pos-seguranca-publica-pos', 'Pós-Graduação em Segurança Pública'),
  p('pos-servico-social-convivencia', 'Pós-Graduação em Serviço Social e Convivência Familiar'),
  p('pos-producao-cultural-arte', 'Produção Cultural, Arte e Entretenimento'),
  p('pos-psicologia-clinica', 'Psicologia Clínica'),
  p('pos-psicologia-clinica-institucional', 'Psicologia Clínica e Institucional'),
  p('pos-psicologia-clinica-ii', 'Psicologia Clínica II'),
  p('pos-psicologia-aprendizagem', 'Psicologia da Aprendizagem'),
  p('pos-psicologia-educacao', 'Psicologia da Educação'),
  p('pos-psicologia-educacional', 'Psicologia Educacional'),
  p('pos-psicologia-hospitalar', 'Psicologia Hospitalar'),
  p('pos-psicologia-organizacional', 'Psicologia Organizacional do Trabalho'),
  p('pos-psicomotricidade', 'Psicomotricidade'),
  p('pos-psicomotricidade-letramento', 'Psicomotricidade e Letramento'),
  p('pos-psicomotricidade-infantil', 'Psicomotricidade na Educação Infantil'),
  p('pos-psicopedagogia', 'Psicopedagogia'),
  p('pos-psicopedagogia-pos', 'Psicopedagogia - Pós'),
  p('pos-psicopedagogia-clinica-institucional', 'Psicopedagogia Clínica e Institucional'),
  p('pos-psicopedagogia-educacao-especial', 'Psicopedagogia Educação Especial'),
  p('pos-redacao-oratoria', 'Redação e Oratória'),
  p('pos-saude-estetica-injetaveis', 'Saúde Estética com Injetáveis'),
  p('pos-saude-publica-familia', 'Saúde Pública com Ênfase em Saúde da Família'),
  p('pos-seguranca-publica-cidadania', 'Segurança Pública e Cidadania'),
  p('pos-servico-social-educacao', 'Serviço Social na Educação'),
  p('pos-supervisao-orientacao-infantil', 'Supervisão e Orientação em Educação Infantil'),
  p('pos-supervisao-orientacao-escolar', 'Supervisão e Orientação Escolar'),
  p('pos-supervisao-orientacao-inspecao', 'Supervisão, Orientação e Inspeção Escolar'),
  p('pos-sustentabilidade-direitos-humanos', 'Sustentabilidade, Responsabilidade Social e Direitos Humanos'),
  p('pos-tdah', 'TDAH – Transtorno de Déficit de Atenção e Hiperatividade'),
  p('pos-tecnologias-educacionais', 'Tecnologias Educacionais'),
  p('pos-tecnologias-educacionais-pos', 'Tecnologias Educacionais - Pós'),
  p('pos-tecnologias-educacionais-pratica', 'Tecnologias Educacionais na Prática Pedagógica'),
  p('pos-terapia-cognitivo-comportamental', 'Terapia Cognitivo-Comportamental'),
  p('pos-terapia-constelacao-familiar', 'Terapia da Constelação Familiar Sistêmica'),
  p('pos-terapia-familiar', 'Terapia Familiar'),
  p('pos-tgd', 'Transtornos Globais do Desenvolvimento (CID F84)'),
  p('pos-tutoria-ead', 'Tutoria em Educação à Distância'),
];

// ---------------------------------------------------------------------------
// Backward compatibility: DADOS_POS_GRADUACAO as string[] for helpers.ts
// ---------------------------------------------------------------------------
export const DADOS_POS_GRADUACAO: string[] = CURSOS_POS_GRADUACAO.map((c) => c.nome);