// =============================================================================
// dadosPosGraduacao.ts
// Fonte de dados dos cursos de pós-graduação da CQP.
// Separe os dados do componente para manter o .tsx limpo e focado em UI.
// =============================================================================

export const DADOS_POS_GRADUACAO: string[] = [
  'A Cultura e Lazer Cultura',
  'A Psicologia dos Contos de Fada',
  'Administração e Supervisão Escolar',
  'Admistração Pública',
  'Agronegócios',
  'Alfabetização e letramento',
  'Alfabetização e Letramento II',
  'Andragogia: Formação de Jovens e Adultos',
  'Arbitragem e Mediação de Conflitos',
  'Arte de Contar História',
  'Arte e Cultura',
  'Arte-Educação',
  'Arteterapia',
  'Atendimento Educacional Especializado - AEE',
  'Atendimento Educacional Especializado com Ênfase em Autismo',
  'Atendimento na Unidade Básica de Saúde - Enfermagem',
  'Atendimento na Unidade Básica de Saúde - Nutrição',
  'Avaliação Psicológica e Psicodiagnóstico',
  'Biomedicina Estética',
  'Braille',
  'Ciências e Meio Ambiente Aplicado à Educação',
  'Ciências Naturais e Sustentabilidade na Educação',
  'Ciências Sociais e Ensino de Geografia',
  'Compliance',
  'Comportamento Humano e Neurociência',
  'Coordenação e Orientação Escolar',
  'Coordenação Educacional',
  'Criminologia',
  'Cuidados Paliativos',
  'Diagnóstico e Avaliação Psicológica',
  'Direito Administrativo',
  'Direito Ambiental',
  'Direito Civil e Processual Civil',
  'Direito da Família',
  'Direito do Trabalho',
  'Direito do Trânsito',
  'Direito Educacional',
  'Direito Eleitoral',
  'Direito Empresarial',
  'Direito Humanos e Perícia Criminal',
  'Direito Imobiliário',
  'Direito Penal e Processo Penal',
  'Direito Penal Militar',
  'Direito Previdenciário',
  'Direito Processual Civil',
  'Direito Público: Constitucional, Administrativo e Tributário',
  'Direito Tributário e Processual Tributário',
  'Docência Do Ensino Superior, Gestão E Tutoria EAD',
  'Docência em Enfermagem',
  'Docência na Educação Básica e Infantil',
  'Docência no Ensino Superior',
  'Docência no Ensino Superior, Médio e Técnico',
  'Educação 5.0',
  'Educação a distância',
  'Educação a Distância - Pós',
  'Educação à Distância II',
  'Educação Ambiental - Pós',
  'Educação Ambiental e Sustentabilidade',
  'Educação de Jovens e Adultos',
  'Educação e Movimentos Sociais',
  'Educação em Foco',
  'Educação Em Tempo Integral',
  'Educação em Unidades de Saúde',
  'Educação Especial - Pós',
  'Educação Especial Avançado',
  'Educação Especial e Inclusiva',
  'Educação Financeira e Matemática Aplicada',
  'Educação Física Adaptada e Inclusiva',
  'Educação Física Escolar',
  'Educação Física Escolar com Ênfase em Educação Especial',
  'Educação Física Escolar e Treinamento Desportivo',
  'Educação Física, Escolar e Recreação',
  'Educação Inclusiva - Pós',
  'Educação Inclusiva e Acessibilidade',
  'Educação Inclusiva e Diversidade Cultural',
  'Educação Infantil',
  'Educação Infantil - Pós Graduação',
  'Educação Infantil de 0 a 5 Anos',
  'Educação Infantil, Alfabetização e Letramento',
  'Educação Infantil, Especial e TGD',
  'Educação Matemática',
  'Educação Musical e o Ensino de Arte',
  'Educação para a Diversidade e Cidadania',
  'Educação Psicomotora',
  'Educação Socioemocional nas Escolas',
  'Educação: Geografia Humana',
  'Emergências Pediátricas',
  'Enfermagem do Trabalho',
  'Enfermagem do Trabalho e Saúde Ocupacional',
  'Enfermagem em Oncologia',
  'Enfermagem em Urgência e Emergência',
  'Engenharia Ambiental',
  'Engenharia Ambiental e Energias Renováveis',
  'Engenharia Ambiental e Saneamento Básico',
  'Engenharia de Manutenção',
  'Engenharia de Segurança do Trabalho',
  'Engenharia de Suprimentos',
  'Ensino de Artes',
  'Ensino de Ciências e Matemática nas Séries Iniciais do Ensino Fundamental',
  'Ensino de Línguas na Educação',
  'Ensino Religioso',
  'Especialização em Análise do Comportamento Aplicada ao Autismo (ABA)',
  'Especialização em Comunicação e Oratória',
  'Especialização em Educ. Especial Inclusiva e Transtorno do Espectro Autista (TEA)',
  'Especialização em Engenharia da Qualidade',
  'Especialização em Engenharia Sanitária e Ambiental',
  'Especialização em Instrumentação Cirúrgica',
  'Especialização em Metodologia do Ensino de História',
  'Especialização em Metodologia do Ensino de Língua Portuguesa',
  'Estatística Aplicada',
  'Estética e Cosmetologia',
  'Estética e História da Arte',
  'Farmácia Clínica e Hospitalar',
  'Farmácia Estética',
  'Formação e Profissão Docente',
  'Gamificação e Aprendizagem Ativa',
  'Gest Escolar Integrad com Ênfase em Supervi, Orientação, Administr e Inspeção',
  'Gestão Ambiental Sustentável',
  'Gestão Bancária e Negócios',
  'Gestão de Clínicas e Consultórias',
  'Gestão de Clínicas e Consultórios',
  'Gestão de Clínicas Odontológicas',
  'Gestão de Investimento',
  'Gestão de Marketing Digital',
  'Gestão de Processos de Produção',
  'Gestão e Planejamento de Projetos Sociais',
  'Gestão Educacional',
  'Gestão Educacional - Pós',
  'Gestão Educacional com Foco na Inclusão',
  'Gestão educacional e inspeção escolar',
  'Gestão em Logística',
  'Gestão em Qualidade em Serviço De Saúde e Hospitalar',
  'Gestão Em Recursos Humanos',
  'Gestão em Saúde Pública',
  'Gestão Escolar',
  'Gestão Escolar e Administração Educacional',
  'Gestão Escolar e Coordenação Pedagógica',
  'Gestão, Licenciamento e Auditoria Ambiental',
  'Gestão, Supervisão, Inspeção e Orientação Escolar',
  'História da Educação',
  'História e Cultura no Brasil',
  'História e Sociedade na Educação',
  'Humanidades, Sociedade e Ética',
  'Informática na Educação',
  'Inovação Pedagógica com Tecnologias Emergentes',
  'Instalação de Sistemas de Energia Solar',
  'Inteligência Artificial',
  'Leitura e Produção Textual no Ensino Fundamental',
  'Letras - Português e Literatura',
  'Libras - Lingua Brasileira de Sinais',
  'Língua e Literatura Brasileira',
  'Linguística e Ensino de Línguas na Educação Básica',
  'Linguística e o estuda das liguagens',
  'Literacia e Comunicação',
  'Literatura Infantojuvenil e Práticas Pedagógicas',
  'Ludopedagogia',
  'Matemática e Cultura Africana na Educação Básica',
  'Matemática Financeira e Estatística',
  'MBA - Administração Financeira e Orçamentária',
  'MBA - Compliance e Gestão de Riscos',
  'MBA - Engenharia de Produção',
  'MBA - Gestão de Departamento Pessoal e Relações Trabalhistas',
  'MBA - Gestão de pessoas e liderança',
  'MBA - Gestão Empresarial',
  'MBA em Administração Hospitalar',
  'MBA em Arbitragem, Conciliação e Mediação',
  'MBA em Assessoria de Comunicação',
  'MBA em Auditoria',
  'MBA Em Auditoria Contábil',
  'MBA em Auditoria e Perícia Contábil',
  'MBA em Auditoria em Saúde',
  'MBA em Coaching',
  'MBA em Comunicação Eleitoral e Marketing Político',
  'MBA em Contabilidade Gerencial',
  'MBA em Controladoria e Finanças',
  'MBA em Controladoria Financeira',
  'MBA em E-Commerce',
  'MBA em Educação Financeira',
  'MBA em ESG – Environmental, Social & Governance',
  'MBA em Gestão Ambiental',
  'MBA em Gestão Aplicada à Engenharia',
  'MBA em Gestão Comercial',
  'MBA em Gestão da Produção',
  'MBA em Gestão da Saúde Física e Mental do Colaborador',
  'MBA em Gestão de Clínicas de Psicologia',
  'MBA em Gestão de Clínicas e Consultórios Veterinários',
  'MBA em Gestão de Custos e Finanças',
  'MBA em Gestão de Drogaria e Farmácia',
  'MBA em Gestão de Eventos',
  'MBA em Gestão de Negócios Imobiliários',
  'MBA em Gestão de Negócios Inovadores',
  'MBA em Gestão de Negócios Internacionais e Comércio Exterior',
  'MBA em Gestão de Obras, Qualidade e Desempenho das Construções',
  'MBA em Gestão de Processos',
  'MBA em Gestão de Projetos',
  'MBA em Gestão de Projetos de Aprendizagem',
  'MBA em Gestão de Seguros e Previdência Privada',
  'MBA em Gestão de Serviços',
  'MBA em Gestão de Turismo e Hospitalidade',
  'MBA em Gestão de Vendas',
  'MBA em Gestão do Agronegócio',
  'MBA em Gestão do Desenvolvimento do Colaborador',
  'MBA em Gestão do Retorno Financeiro de Talentos nos Negócio',
  'MBA em Gestão Estratégica de Cooperativas',
  'MBA em Gestão Estratégica em Compras',
  'MBA em Gestão Estratégica em ESG',
  'MBA em Gestão Fiscal e Tributária',
  'MBA em Gestão Hospitalar',
  'MBA em Gestão Pública',
  'MBA em Inteligência Comercial e de Mercado',
  'MBA em Jornalismo Digital',
  'MBA em Logística e Supply Chain Management',
  'MBA Em Marketing De Varejo, Gestão, Estratégias E Negócios',
  'MBA em Marketing Estratégico Digital',
  'MBA em Mediação e Gestão de Conflitos',
  'MBA em Planejamento para Abertura de Negócio',
  'MBA em Prescrição Estética',
  'MBA em Relações Internacionais',
  'MBA em Segurança Pública',
  'MBA em Startups e Inovação',
  'Mediação Cultural e Educação',
  'Mediação e Tutoria na Educação a Distância',
  'Metodologia do Ensino da Matemática e Física',
  'Metodologia do ensino de educação física',
  'Metodologia do Ensino de Inglês',
  'Metodologia do Ensino Superior nas Várias Modalidades',
  'Metodologias Ativas e Prática Docente',
  'Metodologias Ativas e Tecnologias Educacionais',
  'Metodologias do Ensino de Matemática',
  'Microbiologia',
  'Mundo Digital e Tecnologias para Educação',
  'Neurociência e Aprendizagem na Educação Infantil',
  'Neuropsicologia',
  'Neuropsicologia Clínica',
  'Neuropsicopedagogia',
  'Neuropsicopedagogia Clínica',
  'Nutrição Esportiva',
  'Orientação Educacional',
  'Pedagogia Empresarial e Educação Corporativa',
  'Perícia e Auditoria Contábil',
  'Perícia Econômica Financeira',
  'Planejamento e Gestão de Trânsito',
  'Pós- graduação em direitos humanos',
  'Pós-graduação em Direito Administrativo',
  'Pós-Graduação em Direito Constitucional',
  'Pós-graduação em Direito Tributário',
  'Pós-graduação em gerontologia e gestão da assistência ao idoso',
  'Pós-graduação em Gestão da Qualidade',
  'Pós-Graduação em Gestão da Tecnologia de Informação',
  'Pós-Graduação em Gestão de Recursos Humanos',
  'Pós-graduação em Gestão de Riscos e Ciber segurança',
  'Pós-graduação em gestão estratégica de pessoas',
  'Pós-graduação em Liderança e Desenvolvimento de Equipes',
  'Pós-Graduação em Segurança Pública',
  'Pós-graduação em serviço social e convivência familiar',
  'Produção Cultural, Arte e Entretenimento',
  'Psicologia Clínica',
  'Psicologia Clínica e Institucional',
  'Psicologia Clínica II',
  'Psicologia da Aprendizagem',
  'Psicologia da Educação',
  'Psicologia Educacional',
  'Psicologia Hospitalar',
  'Psicologia organizacional do trabalho',
  'Psicomotricidade',
  'Psicomotricidade e Letramento',
  'Psicomotricidade na Educação Infantil',
  'Psicopedagogia',
  'Psicopedagogia - Pós',
  'Psicopedagogia Clínica e Institucional',
  'Psicopedagogia Educação Especial',
  'Redação E Oratória',
  'Saúde Estética com Injetáveis',
  'Saúde Pública com ênfase em Saúde da Família',
  'Segurança Pública e Cidadania',
  'Serviço Social na Educação',
  'Supervisão e Orientação em Educação Infantil',
  'Supervisão e Orientação Escolar',
  'Supervisão, Orientação e Inspeção Escolar',
  'Sustentabilidade, Responsabilidade Social e Direitos Humanos',
  'TDAH – Transtorno de Déficit de Atenção e Hiperatividade',
  'Tecnologias Educacionais',
  'Tecnologias Educacionais - Pós',
  'Tecnologias Educacionais na Prática Pedagógica',
  'Terapia Cognitivo-Comportamental',
  'Terapia da Constelação Familiar Sistêmica',
  'Terapia Familiar',
  'Transtornos globais do desenvolvimento (CID F84)',
  'Tutoria em Educação à Distância',
];