// helpers.ts
import {
  GraduationCap,
  Scale,
  Heart,
  Briefcase,
  Cog,
  Brain,
  Leaf,
  Monitor,
  Shield,
  BookOpen,
} from 'lucide-react';
import { CategoriaSlug, CategoriaConfig, Modalidade, CursoPosGraduacao } from './types';
import { DADOS_POS_GRADUACAO } from './dadosPosGraduacao';

export const WHATSAPP_NUMBER = '5522998684334';
export const PAGE_SIZE = 12;
export const DEBOUNCE_MS = 250;

export const CONFIG_CATEGORIAS: Record<CategoriaSlug, CategoriaConfig> = {
  educacao: {
    slug: 'educacao',
    label: 'Educação',
    icone: GraduationCap,
    gradient: 'linear-gradient(135deg, #E8F0FE 0%, #D4E4FC 50%, #C5D9F8 100%)',
    badgeBg: '#E8F0FE',
    badgeText: '#1A4A7A',
    keywords: [
      'educação', 'educacional', 'ensino', 'docência', 'docente', 'pedagogia',
      'alfabetização', 'letramento', 'escolar', 'infantil', 'aprendizagem',
      'tutoria', 'ead', 'metodologia', 'didática', 'libras', 'braille',
      'coordenação', 'supervisão', 'orientação', 'inspeção', 'andragogia',
      'professor', 'aee', 'atendimento educacional', 'psicopedagogia',
      'psicomotricidade', 'ludopedagogia', 'neuropsicopedagogia',
      'gestão educacional', 'gestão escolar',
      'história da educação', 'filosofia', 'sociologia', 'educação física',
      'matemática', 'geografia', 'ciências', 'biologia', 'química', 'física',
      'língua', 'linguística', 'literatura', 'letras', 'redação', 'oratória',
      'arte-educação', 'arte e cultura', 'música', 'religioso',
      'informática na educação', 'tecnologias educacionais',
      'gamificação', 'inovação pedagógica', 'educação 5.0',
      'mundo digital', 'educação a distância', 'mediação',
      'educação inclusiva', 'educação especial', 'diversidade',
      'educação ambiental', 'educação financeira', 'educação socioemocional',
      'educação em tempo integral', 'educação de jovens e adults',
      'serviço social na educação', 'pedagogia empresarial',
      'educação corporativa', 'formação', 'profissão docente',
      'produção cultural', 'arte', 'cultura', 'história',
      'literatura infantojuvenil', 'contação de história',
      'arte de contar', 'arteterapia', 'psicologia da educação',
      'psicologia educacional', 'neurociência e aprendizagem',
      'tdah', 'transtornos globais', 'tea', 'autismo',
      'especialização em metodologia', 'especialização em educ',
      'educação matemática', 'educação musical',
      'educação física escolar', 'educação física adaptada',
      'educação infantil', 'educação básica',
      'supervisão e orientação', 'inspeção escolar',
      'gestão, supervisão', 'coordenação pedagógica',
      'administração e supervisão escolar',
      'educação em unidades de saúde',
      'educação e movimentos sociais',
      'educação em foco',
      'educação para a diversidade',
      'educação: geografia humana',
      'ciências sociais e ensino',
      'ciências naturais e sustentabilidade',
      'ciências e meio ambiente',
      'estatística aplicada',
      'matemática financeira e estatística',
      'matemática e cultura africana',
      'leitura e produção textual',
      'língua e literatura brasileira',
      'linguística e o estudo',
      'literacia e comunicação',
      'comunicação e oratória',
      'especialização em comunicação',
    ],
  },
  direito: {
    slug: 'direito',
    label: 'Direito',
    icone: Scale,
    gradient: 'linear-gradient(135deg, #FEF3E2 0%, #FDE6C8 50%, #FCD9AE 100%)',
    badgeBg: '#FEF3E2',
    badgeText: '#7A4A1A',
    keywords: [
      'direito', 'jurídico', 'processual', 'penal', 'civil', 'tributário',
      'constitucional', 'eleitoral', 'previdenciário', 'arbitragem',
      'mediação de conflitos', 'criminologia', 'perícia criminal',
      'direitos humanos', 'imobiliário', 'empresarial', 'administrativo',
      'trabalho', 'trânsito', 'família', 'militar', 'público',
      'compliance', 'lgpd', 'proteção de dados',
    ],
  },
  saude: {
    slug: 'saude',
    label: 'Saúde',
    icone: Heart,
    gradient: 'linear-gradient(135deg, #FDE8EC 0%, #FCD5DD 50%, #FAC2CD 100%)',
    badgeBg: '#FDE8EC',
    badgeText: '#7A1A3A',
    keywords: [
      'enfermagem', 'saúde', 'farmácia', 'nutrição', 'biomedicina',
      'hospitalar', 'clínica', 'estética', 'emergência', 'oncologia',
      'pediátrica', 'odontológica', 'cuidados paliativos',
      'instrumentação cirúrgica', 'gerontologia', 'idoso',
      'microbiologia', 'cosmetologia', 'estética e cosmetologia',
      'biomedicina estética', 'farmácia estética', 'farmácia clínica',
      'saúde estética', 'prescrição estética',
      'saúde pública', 'saúde da família', 'saúde ocupacional',
      'gestão em qualidade em serviço de saúde',
      'gestão de clínicas', 'gestão de consultórios',
      'auditoria em saúde', 'administração hospitalar',
      'gestão hospitalar', 'gestão da saúde física',
      'nutrição esportiva', 'enfermagem do trabalho',
      'enfermagem em urgência', 'emergências pediátricas',
      'enfermagem em oncologia', 'atendimento na unidade básica',
      'diagnóstico', 'avaliação psicológica', 'psicodiagnóstico',
      'psicologia clínica', 'psicologia hospitalar',
      'neuropsicologia', 'terapia cognitivo-comportamental',
      'terapia familiar', 'terapia da constelação',
      'psicologia organizacional', 'avaliação psicológica',
      'cuidados paliativos',
    ],
  },
  gestao: {
    slug: 'gestao',
    label: 'Gestão & Negócios',
    icone: Briefcase,
    gradient: 'linear-gradient(135deg, #E0F5F5 0%, #CCEEEE 50%, #B8E6E6 100%)',
    badgeBg: '#E0F5F5',
    badgeText: '#0C6161',
    keywords: [
      'gestão', 'mba', 'administração', 'compliance', 'marketing',
      'logística', 'recursos humanos', 'finanças', 'controladoria',
      'auditoria', 'liderança', 'coaching', 'startups', 'e-commerce',
      'vendas', 'negócios', 'turismo', 'eventos', 'agronegócios',
      'cooperativas', 'comércio exterior', 'supply chain',
      'departamento pessoal', 'gestão de pessoas', 'gestão empresarial',
      'gestão comercial', 'gestão da produção', 'gestão de projetos',
      'gestão de custos', 'gestão fiscal', 'gestão tributária',
      'gestão pública', 'gestão de seguros', 'gestão de serviços',
      'gestão estratégica', 'gestão de processos', 'planejamento',
      'controladoria financeira', 'contabilidade gerencial',
      'perícia contábil', 'perícia econômica', 'auditoria contábil',
      'gestão bancária', 'gestão de investimento',
      'gestão de marketing digital', 'marketing estratégico',
      'marketing de varejo', 'marketing político',
      'comunicação eleitoral', 'assessoria de comunicação',
      'jornalismo digital', 'relações internacionais',
      'gestão de negócios imobiliários', 'gestão de negócios inovadores',
      'gestão de negócios internacionais', 'gestão do agronegócio',
      'gestão de turismo', 'gestão de eventos',
      'gestão de drogaria', 'gestão de clínicas e consultórios',
      'gestão de clínicas odontológicas', 'gestão de clínicas de psicologia',
      'gestão de clínicas e consultórios veterinários',
      'gestão em logística', 'gestão de obras',
      'gestão de processos de produção', 'gestão da qualidade',
      'gestão da tecnologia de informação',
      'planejamento e gestão de trânsito',
      'gestão e planejamento de projetos sociais',
      'gestão, licenciamento e auditoria ambiental',
      'gestão ambiental sustentável',
      'gestão de segurança pública', 'segurança pública',
      'administração pública', 'gestão em saúde pública',
      'gestão de recursos humanos', 'gestão em recursos humanos',
      'liderança e desenvolvimento de equipes',
      'gestão estratégica de pessoas',
      'gestão do desenvolvimento do colaborador',
      'gestão do retorno financeiro',
      'planejamento para abertura de negócio',
      'inteligência comercial',
      'esg', 'environmental, social',
      'gestão estratégica em esg',
      'mba em esg',
      'gestão aplicada à engenharia',
      'mba em gestão ambiental',
      'mba em gestão de',
      'mba em administração',
      'mba em auditoria',
      'mba em coaching',
      'mba em comunicação',
      'mba em contabilidade',
      'mba em controladoria',
      'mba em e-commerce',
      'mba em educação financeira',
      'mba em gestão',
      'mba em inteligência',
      'mba em jornalismo',
      'mba em logística',
      'mba em marketing',
      'mba em mediação',
      'mba em planejamento',
      'mba em prescrição',
      'mba em relações',
      'mba em segurança',
      'mba em startups',
      'pós-graduação em gestão',
      'pós-graduação em liderança',
      'pós-graduação em serviço social',
      'serviço social e convivência',
      'gestão de conflitos',
      'mediação e gestão de conflitos',
      'arbitragem, conciliação e mediação',
      'comércio exterior',
      'supply chain',
    ],
  },
  engenharia: {
    slug: 'engenharia',
    label: 'Engenharia',
    icone: Cog,
    gradient: 'linear-gradient(135deg, #E8EAF6 0%, #D1D5EE 50%, #BCC1E6 100%)',
    badgeBg: '#E8EAF6',
    badgeText: '#2A2A7A',
    keywords: [
      'engenharia', 'produção', 'manutenção', 'suprimentos',
      'energia', 'solar', 'saneamento', 'qualidade',
      'instalação de sistemas', 'segurança do trabalho',
      'engenharia sanitária', 'engenharia ambiental',
      'engenharia da qualidade', 'engenharia de segurança',
      'engenharia de manutenção', 'engenharia de suprimentos',
      'engenharia de produção',
    ],
  },
  psicologia: {
    slug: 'psicologia',
    label: 'Psicologia',
    icone: Brain,
    gradient: 'linear-gradient(135deg, #F3E8F8 0%, #E8D5F2 50%, #DCC2EC 100%)',
    badgeBg: '#F3E8F8',
    badgeText: '#5A1A7A',
    keywords: [
      'psicologia', 'neurociência', 'neuropsicologia', 'neuropsicopedagogia',
      'psicomotricidade', 'psicopedagogia', 'tdah', 'tea', 'autismo',
      'comportamento', 'terapia cognitivo', 'terapia familiar',
      'terapia da constelação', 'psicanálise', 'aba',
      'análise do comportamento', 'psicologia clínica',
      'psicologia hospitalar', 'psicologia organizacional',
      'psicologia da aprendizagem', 'psicologia educacional',
      'neuropsicologia clínica', 'neuropsicopedagogia clínica',
      'psicologia clínica e institucional', 'psicodiagnóstico',
      'avaliação psicológica', 'diagnóstico e avaliação',
      'comportamento humano e neurociência',
      'transtorno do espectro autista', 'transtornos globais',
      'transtorno de déficit', 'psicologia dos contos',
      'psicomotricidade e letramento', 'psicomotricidade na educação',
      'psicopedagogia clínica', 'psicopedagogia educação especial',
      'psicopedagogia - pós',
    ],
  },
  'meio-ambiente': {
    slug: 'meio-ambiente',
    label: 'Meio Ambiente',
    icone: Leaf,
    gradient: 'linear-gradient(135deg, #E8F5E9 0%, #D0EBD2 50%, #B9E0BC 100%)',
    badgeBg: '#E8F5E9',
    badgeText: '#1A5A2A',
    keywords: [
      'ambiental', 'sustentabilidade', 'esg', 'meio ambiente',
      'ecologia', 'saneamento', 'energias renováveis',
      'gestão ambiental', 'educação ambiental',
      'sustentabilidade, responsabilidade social',
      'engenharia ambiental e energias',
      'engenharia ambiental e saneamento',
      'gestão ambiental sustentável',
      'gestão, licenciamento e auditoria ambiental',
      'ciências e meio ambiente',
    ],
  },
  tecnologia: {
    slug: 'tecnologia',
    label: 'Tecnologia',
    icone: Monitor,
    gradient: 'linear-gradient(135deg, #E0F2F7 0%, #C8E6F0 50%, #B0DAE8 100%)',
    badgeBg: '#E0F2F7',
    badgeText: '#1A4A6A',
    keywords: [
      'tecnologia', 'informática', 'inteligência artificial',
      'digital', 'gamificação', 'inovação', 'ti',
      'tecnologias educacionais', 'mundo digital',
      'inovação pedagógica com tecnologias',
      'tecnologias educacionais na prática',
      'tecnologias educacionais - pós',
      'inteligência artificial',
      'gestão da tecnologia de informação',
      'pós-graduação em gestão da tecnologia',
      'mba em gestão de negócios inovadores',
      'mba em startups e inovação',
      'mba em e-commerce',
      'mba em inteligência comercial',
      'mba em marketing estratégico digital',
      'mba em gestão de marketing digital',
      'mba em jornalismo digital',
      'marketing digital',
      'gestão de marketing digital',
      'marketing estratégico digital',
      'marketing de varejo, gestão, estratégias e negócios',
      'mba em marketing de varejo',
      'mba em comunicação eleitoral e marketing político',
      'mba em assessoria de comunicação',
      'mba em gestão de negócios internacionais',
      'mba em relações internacionais',
      'mba em logística e supply chain',
      'mba em gestão de projetos',
      'mba em gestão de processos',
      'mba em gestão da produção',
      'mba em engenharia de produção',
      'mba em controladoria e finanças',
      'mba em controladoria financeira',
      'mba em contabilidade gerencial',
      'mba em auditoria',
      'mba em auditoria contábil',
      'mba em auditoria e perícia contábil',
      'mba em gestão fiscal e tributária',
      'mba em gestão de custos e finanças',
      'mba em administração financeira e orçamentária',
      'mba em gestão de seguros e previdência privada',
      'mba em gestão de investimento',
      'mba em gestão bancária e negócios',
      'mba em gestão comercial',
      'mba em gestão de vendas',
      'mba em gestão de serviços',
      'mba em gestão de turismo e hospitalidade',
      'mba em gestão de eventos',
      'mba em gestão do agronegócio',
      'mba em gestão de negócios imobiliários',
      'mba em gestão estratégica de cooperativas',
      'mba em gestão estratégica em compras',
      'mba em gestão estratégica em esg',
      'mba em gestão de obras, qualidade e desempenho',
      'mba em gestão aplicada à engenharia',
      'mba em gestão ambiental',
      'mba em gestão de drogaria e farmácia',
      'mba em gestão de clínicas e consultórios veterinários',
      'mba em gestão de clínicas de psicologia',
      'mba em gestão de clínicas e consultórios',
      'mba em gestão de clínicas odontológicas',
      'mba em gestão hospitalar',
      'mba em administração hospitalar',
      'mba em auditoria em saúde',
      'mba em gestão da saúde física e mental',
      'mba em gestão de pessoas e liderança',
      'mba em gestão empresarial',
      'mba em gestão do desenvolvimento do colaborador',
      'mba em gestão do retorno financeiro de talentos',
      'mba em gestão de departamento pessoal',
      'mba em compliance e gestão de riscos',
      'mba em segurança pública',
      'mba em gestão pública',
      'mba em planejamento para abertura de negócio',
      'mba em prescrição estética',
      'mba em educação financeira',
      'mba em arbitragem, conciliação e mediação',
      'mba em mediação e gestão de conflitos',
      'mba em gestão de projetos de aprendizagem',
      'pós-graduação em gestão da qualidade',
      'pós-graduação em gestão de recursos humanos',
      'pós-graduação em gestão de riscos e ciber segurança',
      'pós-graduação em gestão estratégica de pessoas',
      'pós-graduação em liderança e desenvolvimento de equipes',
      'pós-graduação em segurança pública',
      'pós-graduação em serviço social e convivência familiar',
      'pós-graduação em gerontologia e gestão da assistência ao idoso',
      'pós-graduação em direitos humanos',
      'pós-graduação em direito administrativo',
      'pós-graduação em direito constitucional',
      'pós-graduação em direito tributário',
      'especialização em engenharia da qualidade',
      'especialização em engenharia sanitária e ambiental',
      'especialização em instrumentação cirúrgica',
      'especialização em metodologia do ensino de história',
      'especialização em metodologia do ensino de língua portuguesa',
      'especialização em comunicação e oratória',
      'especialização em educ. especial inclusiva e transtorno do espectro autista (tea)',
      'especialização em análise do comportamento aplicada ao autismo (aba)',
      'compliance',
      'compliance e gestão de riscos',
      'gestão de riscos e cibersegurança',
      'pós-graduação em gestão de riscos e ciber segurança',
    ],
  },
  seguranca: {
    slug: 'seguranca',
    label: 'Segurança',
    icone: Shield,
    gradient: 'linear-gradient(135deg, #FBE9E7 0%, #F8D7D3 50%, #F4C5BF 100%)',
    badgeBg: '#FBE9E7',
    badgeText: '#7A2A1A',
    keywords: [
      'segurança pública', 'segurança do trabalho', 'perícia criminal',
      'criminologia', 'segurança e cidadania', 'defesa civil',
      'gestão de segurança', 'segurança patrimonial',
      'engenharia de segurança do trabalho',
      'pós-graduação em segurança pública',
      'mba em segurança pública',
      'direito humanos e perícia criminal',
      'perícia e auditoria',
      'perícia econômica financeira',
      'perícia contábil',
      'auditoria e perícia contábil',
      'mba em auditoria e perícia',
      'mba em perícia',
    ],
  },
  outros: {
    slug: 'outros',
    label: 'Outros',
    icone: BookOpen,
    gradient: 'linear-gradient(135deg, #F0F0F0 0%, #E5E5E5 50%, #DADADA 100%)',
    badgeBg: '#F0F0F0',
    badgeText: '#444444',
    keywords: [],
  },
};

export const TABS: CategoriaConfig[] = [
  CONFIG_CATEGORIAS.educacao,
  CONFIG_CATEGORIAS.direito,
  CONFIG_CATEGORIAS.saude,
  CONFIG_CATEGORIAS.gestao,
  CONFIG_CATEGORIAS.engenharia,
  CONFIG_CATEGORIAS.psicologia,
  CONFIG_CATEGORIAS['meio-ambiente'],
  CONFIG_CATEGORIAS.tecnologia,
  CONFIG_CATEGORIAS.seguranca,
  CONFIG_CATEGORIAS.outros,
];

export function normalize(str: string): string {
  return str
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

export function categorizarCurso(titulo: string): CategoriaSlug {
  const norm = normalize(titulo);
  const categorias = TABS.filter((c) => c.slug !== 'outros');

  let bestMatch: CategoriaSlug = 'outros';
  let bestScore = 0;

  for (const cat of categorias) {
    let score = 0;
    for (const kw of cat.keywords) {
      const kwNorm = normalize(kw);
      if (norm.includes(kwNorm)) {
        score += kwNorm.length;
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = cat.slug;
    }
  }

  return bestMatch;
}

export function getModalidade(titulo: string): Modalidade {
  const semipresencialKeywords = [
    'enfermagem', 'farmácia', 'biomedicina', 'instrumentação',
    'cirúrgica', 'emergência', 'odontológica', 'solar',
    'nutrição esportiva', 'estética e cosmetologia',
    'biomedicina estética', 'farmácia estética',
    'saúde estética com injetáveis', 'prescrição estética',
    'engenharia de segurança', 'engenharia de manutenção',
    'engenharia de suprimentos', 'instalação de sistemas',
    'microbiologia',
  ];
  const norm = normalize(titulo);
  return semipresencialKeywords.some((k) => norm.includes(normalize(k)))
    ? 'SEMIPRESENCIAL'
    : 'EAD';
}

export function buildCursos(): CursoPosGraduacao[] {
  return DADOS_POS_GRADUACAO.map((titulo, i) => ({
    id: `pos-${i}`,
    titulo: titulo.trim(),
    categoria: categorizarCurso(titulo),
    modalidade: getModalidade(titulo),
  }));
}

export const TODOS_OS_CURSOS_POS: CursoPosGraduacao[] = buildCursos();